#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 3
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

bspc rule -a Pavucontrol state=floating
bspc rule -a Ulauncher state=floating border=off
