# Set prefix to Ctrl+Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Move between windows with <prefix> + h/l
bind h previous-window
bind l next-window

# Use truecolor
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Help tmux detect when a pane gains/loses focus
set-option -g focus-events on

# Start indexing at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Enable mouse support
set -g mouse on

# Reload config with <prefix> + r
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'

run '~/.tmux/plugins/tpm/tpm'

